name: Docs

on:
  push:
    paths:
      - 'docusaurus/**'

jobs:
  gh-pages:
    name: "Github pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd docusaurus/ install
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd docusaurus/ build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docusaurus/build
          external_repository: project-openubl/xbuilder-docs
          publish_branch: master
